// Generated by CoffeeScript 1.12.7
var StorageData;

StorageData = (function() {
  function StorageData() {
    this.initialize.apply(this, arguments);
  }

  StorageData.prototype = Object.create(StorageData.prototype);

  StorageData.prototype.constructor = StorageData;

  StorageData.prototype.initialize = function() {
    this.SEED_COUNT = 256;
    this.SEED_LINK = "-";
    this.KEY_MATRIX = 36;
    this.key = "";
    this.inn = [];
    this.seed = "";
    this.init_seed = "";
    this.count_seed = "";
    this.initKey();
    this.initSeed();
    return true;
  };

  Object.defineProperties(StorageData.prototype, {
    id: {
      get: function() {
        return Utils.radixNum(this.key.substring(0, 5), 36, 10).padZero(8);
      },
      configurable: true
    }
  });

  StorageData.prototype.initSeed = function() {
    var i, j, ref;
    for (i = j = 0, ref = this.SEED_COUNT; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      this.seed += i ? this.SEED_LINK : "";
      this.seed += Utils.radixNum(this.seedNext(Math.randomInt(65535), i), 10, 36);
      this.count_seed += i ? this.SEED_LINK : "";
      this.count_seed += Utils.radixNum(0);
    }
    this.init_seed = this.seed;
    return true;
  };

  StorageData.prototype.initKey = function() {
    var i, j, ref;
    for (i = j = 0, ref = this.KEY_MATRIX * this.KEY_MATRIX; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      this.key += Utils.radixNum(Math.randomInt(this.KEY_MATRIX), 10, this.KEY_MATRIX);
    }
    return true;
  };

  StorageData.prototype.getKey = function(location) {
    var i, j, k, ref, ref1, result1, result2, t1, t2, x, y;
    x = location % this.KEY_MATRIX;
    y = parseInt(location / this.KEY_MATRIX) % this.KEY_MATRIX;
    t1 = [y * this.KEY_MATRIX + (x % 6), y * this.KEY_MATRIX + ((x + 1) % 6), y * this.KEY_MATRIX + ((x + 2) % 6), y * this.KEY_MATRIX + ((x + 3) % 6), y * this.KEY_MATRIX + ((x + 4) % 6), y * this.KEY_MATRIX + ((x + 5) % 6), (y + 1) * this.KEY_MATRIX + (x % 6), (y + 1) * this.KEY_MATRIX + ((x + 1) % 6), (y + 1) * this.KEY_MATRIX + ((x + 2) % 6), (y + 1) * this.KEY_MATRIX + ((x + 3) % 6), (y + 1) * this.KEY_MATRIX + ((x + 4) % 6), (y + 1) * this.KEY_MATRIX + ((x + 5) % 6), (y + 2) * this.KEY_MATRIX + (x % 6), (y + 2) * this.KEY_MATRIX + ((x + 1) % 6), (y + 2) * this.KEY_MATRIX + ((x + 2) % 6), (y + 2) * this.KEY_MATRIX + ((x + 3) % 6), (y + 2) * this.KEY_MATRIX + ((x + 4) % 6), (y + 2) * this.KEY_MATRIX + ((x + 5) % 6), (y + 3) * this.KEY_MATRIX + (x % 6), (y + 3) * this.KEY_MATRIX + ((x + 1) % 6), (y + 3) * this.KEY_MATRIX + ((x + 2) % 6), (y + 3) * this.KEY_MATRIX + ((x + 3) % 6), (y + 3) * this.KEY_MATRIX + ((x + 4) % 6), (y + 3) * this.KEY_MATRIX + ((x + 5) % 6), (y + 4) * this.KEY_MATRIX + (x % 6), (y + 4) * this.KEY_MATRIX + ((x + 1) % 6), (y + 4) * this.KEY_MATRIX + ((x + 2) % 6), (y + 4) * this.KEY_MATRIX + ((x + 3) % 6), (y + 4) * this.KEY_MATRIX + ((x + 4) % 6), (y + 4) * this.KEY_MATRIX + ((x + 5) % 6), (y + 5) * this.KEY_MATRIX + (x % 6), (y + 5) * this.KEY_MATRIX + ((x + 1) % 6), (y + 5) * this.KEY_MATRIX + ((x + 2) % 6), (y + 5) * this.KEY_MATRIX + ((x + 3) % 6), (y + 5) * this.KEY_MATRIX + ((x + 4) % 6), (y + 5) * this.KEY_MATRIX + ((x + 5) % 6)];
    t2 = [x * this.KEY_MATRIX + (y % 6), x * this.KEY_MATRIX + ((y + 1) % 6), x * this.KEY_MATRIX + ((y + 2) % 6), x * this.KEY_MATRIX + ((y + 3) % 6), x * this.KEY_MATRIX + ((y + 4) % 6), x * this.KEY_MATRIX + ((y + 5) % 6), (x + 1) * this.KEY_MATRIX + (y % 6), (x + 1) * this.KEY_MATRIX + ((y + 1) % 6), (x + 1) * this.KEY_MATRIX + ((y + 2) % 6), (x + 1) * this.KEY_MATRIX + ((y + 3) % 6), (x + 1) * this.KEY_MATRIX + ((y + 4) % 6), (x + 1) * this.KEY_MATRIX + ((y + 5) % 6), (x + 2) * this.KEY_MATRIX + (y % 6), (x + 2) * this.KEY_MATRIX + ((y + 1) % 6), (x + 2) * this.KEY_MATRIX + ((y + 2) % 6), (x + 2) * this.KEY_MATRIX + ((y + 3) % 6), (x + 2) * this.KEY_MATRIX + ((y + 4) % 6), (x + 2) * this.KEY_MATRIX + ((y + 5) % 6), (x + 3) * this.KEY_MATRIX + (y % 6), (x + 3) * this.KEY_MATRIX + ((y + 1) % 6), (x + 3) * this.KEY_MATRIX + ((y + 2) % 6), (x + 3) * this.KEY_MATRIX + ((y + 3) % 6), (x + 3) * this.KEY_MATRIX + ((y + 4) % 6), (x + 3) * this.KEY_MATRIX + ((y + 5) % 6), (x + 4) * this.KEY_MATRIX + (y % 6), (x + 4) * this.KEY_MATRIX + ((y + 1) % 6), (x + 4) * this.KEY_MATRIX + ((y + 2) % 6), (x + 4) * this.KEY_MATRIX + ((y + 3) % 6), (x + 4) * this.KEY_MATRIX + ((y + 4) % 6), (x + 4) * this.KEY_MATRIX + ((y + 5) % 6), (x + 5) * this.KEY_MATRIX + (y % 6), (x + 5) * this.KEY_MATRIX + ((y + 1) % 6), (x + 5) * this.KEY_MATRIX + ((y + 2) % 6), (x + 5) * this.KEY_MATRIX + ((y + 3) % 6), (x + 5) * this.KEY_MATRIX + ((y + 4) % 6), (+5) * this.KEY_MATRIX + ((y + 5) % 6)];
    for (i = j = 0, ref = t1.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      t1[i] = parseInt(Utils.radixNum(this.key[t1[i]], this.KEY_MATRIX, 10));
    }
    for (i = k = 0, ref1 = t2.length; 0 <= ref1 ? k < ref1 : k > ref1; i = 0 <= ref1 ? ++k : --k) {
      t2[i] = parseInt(Utils.radixNum(this.key[t2[i]], this.KEY_MATRIX, 10));
    }
    result1 = (t1[0] * t1[11] * t1[16] * t1[21] * t1[26] * t1[31] + t1[1] * t1[6] * t1[17] * t1[22] * t1[27] * t1[32] + t1[2] * t1[7] * t1[12] * t1[23] * t1[28] * t1[33] + t1[3] * t1[8] * t1[13] * t1[18] * t1[29] * t1[34] + t1[4] * t1[9] * t1[14] * t1[19] * t1[24] * t1[35] + t1[5] * t1[10] * t1[15] * t1[20] * t1[25] * t1[30]) - (t1[0] * t1[7] * t1[14] * t1[21] * t1[28] * t1[35] + t1[1] * t1[8] * t1[15] * t1[22] * t1[29] * t1[30] + t1[2] * t1[9] * t1[16] * t1[23] * t1[24] * t1[31] + t1[3] * t1[10] * t1[17] * t1[18] * t1[25] * t1[32] + t1[4] * t1[11] * t1[12] * t1[19] * t1[26] * t1[33] + t1[5] * t1[6] * t1[13] * t1[20] * t1[27] * t1[34]);
    result2 = (t2[0] * t2[11] * t2[16] * t2[21] * t2[26] * t2[31] + t2[1] * t2[6] * t2[17] * t2[22] * t2[27] * t2[32] + t2[2] * t2[7] * t2[12] * t2[23] * t2[28] * t2[33] + t2[3] * t2[8] * t2[13] * t2[18] * t2[29] * t2[34] + t2[4] * t2[9] * t2[14] * t2[19] * t2[24] * t2[35] + t2[5] * t2[10] * t2[15] * t2[20] * t2[25] * t2[30]) - (t2[0] * t2[7] * t2[14] * t2[21] * t2[28] * t2[35] + t2[1] * t2[8] * t2[15] * t2[22] * t2[29] * t2[30] + t2[2] * t2[9] * t2[16] * t2[23] * t2[24] * t2[31] + t2[3] * t2[10] * t2[17] * t2[18] * t2[25] * t2[32] + t2[4] * t2[11] * t2[12] * t2[19] * t2[26] * t2[33] + t2[5] * t2[6] * t2[13] * t2[20] * t2[27] * t2[34]);
    return [result1, result2];
  };

  StorageData.prototype.keyNumber = function(location, val) {
    var arr;
    arr = this.getKey(location);
    return Utils.radixNum((val - arr[1] * -2) * (arr[0] + 3), 10, 36);
  };

  StorageData.prototype.valueNumber = function(location, val) {
    var arr;
    arr = this.getKey(location);
    return Math.round(Utils.radixNum(val, 36, 10) / (arr[0] + 3) - arr[1] * 2);
  };

  StorageData.prototype.getInn = function(location) {
    var x, y;
    x = location % this.KEY_MATRIX;
    y = parseInt(location / this.KEY_MATRIX);
    if (!this.inn[y]) {
      this.inn[y] = [];
    }
    if (!this.inn[y][x]) {
      this.inn[y][x] = this.keyNumber(location(0));
    }
    return this.valueNumber(location(this.inn[y][x]));
  };

  StorageData.prototype.setInn = function(location, val) {
    var x, y;
    x = location % this.KEY_MATRIX;
    y = parseInt(location / this.KEY_MATRIX);
    if (!this.inn[y]) {
      this.inn[y] = [];
    }
    this.inn[y][x] = this.keyNumber(location, val);
    return true;
  };

  StorageData.prototype.idleInn = function() {
    var c, i, item, j, ref;
    c = 0;
    for (item in this.inn) {
      for (i = j = 0, ref = this.KEY_MATRIX; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        if (!this.inn[c][i]) {
          return c * this.KEY_MATRIX + i;
        }
      }
      c++;
    }
    return c * this.KEY_MATRIX;
  };

  StorageData.prototype.pro = function(mode, promax) {
    return this.getSeed(mode) % (promax || 100);
  };

  StorageData.prototype.getSeed = function(mode) {
    var seed, seed_arr, seed_count;
    seed_arr = this.seed.split(this.SEED_LINK);
    seed_count = this.count_seed.split(this.SEED_LINK);
    seed = this.seedNext(Utils.radixNum(seed_arr[mode % this.SEED_COUNT], 36, 10), mode % this.SEED_COUNT);
    seed_arr[mode % this.SEED_COUNT] = Utils.radixNum(seed, 10, 36);
    seed_count[mode % this.SEED_COUNT]++;
    this.count_seed = seed_count.join(this.SEED_LINK);
    this.seed = seed_arr.join(this.SEED_LINK);
    return seed;
  };

  StorageData.prototype.seedNext = function(seed, mode) {
    switch (mode % 4) {
      case 0:
        seed = (seed * 3877 + 139968) % 29573;
        break;
      case 1:
        seed = (seed * 421 + 259200) % 54773;
        break;
      case 2:
        seed = (seed * 9301 + 49297) % 233280;
        break;
      case 3:
        seed = (seed * 281 + 134456) % 28411;
    }
    return Math.round(seed);
  };

  return StorageData;

})();

LIM.$data = new StorageData();
