// Generated by CoffeeScript 1.12.7
var StorageSave;

StorageSave = (function() {
  function StorageSave() {}

  StorageSave.key = CryptoJS.enc.Hex.parse('123318efc4b6388888af51a6cd932b12');

  StorageSave.makeSaveContents = function(savefileId) {
    var contents, contentsString, encrypted;
    contents = {};
    if (savefileId < 0) {
      contents.storage = {};
    } else if (savefileId === 0) {
      contents.storage = {};
    } else {
      contents.storage = {
        key: LIM.$data.key,
        seed: LIM.$data.seed,
        init_seed: LIM.$data.init_seed,
        count_seed: LIM.$data.count_seed,
        inn: LIM.$data.inn,
        bool: LIM.$bool.arr,
        number: LIM.$number.arr
      };
    }
    contentsString = JSON.stringify(contents);
    encrypted = CryptoJS.AES.encrypt(contentsString, CryptoJS.enc.Utf8.parse(this.key), {
      mode: CryptoJS.mode.ECB,
      padding: CryptoJS.pad.Pkcs7
    });
    return encrypted.toString();
  };

  StorageSave.loadSaveContents = function(savefileId, data) {
    var contents;
    if (!data) {
      return;
    }
    contents = JSON.parse(CryptoJS.AES.decrypt(data, CryptoJS.enc.Utf8.parse(this.key), {
      mode: CryptoJS.mode.ECB,
      padding: CryptoJS.pad.Pkcs7
    }).toString(CryptoJS.enc.Utf8));
    if (savefileId < 0) {
      return true;
    } else if (savefileId === 0) {
      return true;
    } else {
      LIM.$data.key = contents.storage.key;
      LIM.$data.seed = contents.storage.seed;
      LIM.$data.init_seed = contents.storage.init_seed;
      LIM.$data.count_seed = contents.storage.count_seed;
      LIM.$data.inn = contents.storage.inn;
      LIM.$bool.arr = contents.storage.bool;
      LIM.$number.arr = contents.storage.number;
      return true;
    }
  };

  StorageSave.save = function(savefileId) {
    if (Utils.isNwjs()) {
      this.saveToLocalFile(savefileId, this.makeSaveContents(savefileId));
    } else {
      this.saveToWebStorage(savefileId, this.makeSaveContents(savefileId));
    }
    return true;
  };

  StorageSave.load = function(savefileId) {
    if (Utils.isNwjs()) {
      this.loadSaveContents(savefileId, this.loadFromLocalFile(savefileId));
    } else {
      this.loadSaveContents(savefileId, this.loadFromWebStorage(savefileId));
    }
    return true;
  };

  StorageSave.saveToLocalFile = function(savefileId, json) {
    var dirPath, filePath, fs;
    fs = require('fs');
    dirPath = this.localFileDirectoryPath();
    filePath = this.localFilePath(savefileId);
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath);
    }
    fs.writeFileSync(filePath, json);
    return true;
  };

  StorageSave.loadFromLocalFile = function(savefileId) {
    var data, filePath, fs;
    data = null;
    fs = require('fs');
    filePath = this.localFilePath(savefileId);
    if (fs.existsSync(filePath)) {
      data = fs.readFileSync(filePath, {
        encoding: 'utf8'
      });
    }
    return data;
  };

  StorageSave.saveToWebStorage = function(savefileId, json) {
    var key;
    key = this.webStorageKey(savefileId);
    localStorage.setItem(key, json);
    return true;
  };

  StorageSave.loadFromWebStorage = function(savefileId) {
    var data, key;
    key = this.webStorageKey(savefileId);
    data = localStorage.getItem(key);
    return data;
  };

  StorageSave.localFileDirectoryPath = function() {
    var base, path;
    path = require('path');
    base = path.dirname(process.mainModule.filename);
    return path.join(base, 'save/');
  };

  StorageSave.localFilePath = function(savefileId) {
    var name;
    name = savefileId < 0 ? 'config.lim' : savefileId === 0 ? 'global.lim' : 'save%1.lim'.format(savefileId);
    return this.localFileDirectoryPath() + name;
  };

  StorageSave.webStorageKey = function(savefileId) {
    if (savefileId < 0) {
      return 'RPG Config';
    } else if (savefileId === 0) {
      return 'LIM Global';
    } else {
      return 'LIM save%1'.format(savefileId);
    }
  };

  return StorageSave;

})();
