// Generated by CoffeeScript 1.12.7
var StorageBool;

StorageBool = (function() {
  function StorageBool() {
    this.initialize.apply(this, arguments);
  }

  StorageBool.prototype = Object.create(StorageBool.prototype);

  StorageBool.prototype.constructor = StorageBool;

  StorageBool.prototype.initialize = function() {
    this.arr = [];
    return true;
  };

  StorageBool.prototype.get = function(id) {
    var arr, key;
    arr = parseInt(id / 16);
    if (this.arr[arr] != null) {
      key = this.getGroup(arr);
      return key[id % 16] > 1;
    } else {
      return false;
    }
  };

  StorageBool.prototype.set = function(id, bool) {
    var arr, key;
    arr = parseInt(id / 16);
    if (this.arr[arr] === null) {
      this.arr[arr] = LIM.$data.idleInn();
    }
    key = this.getGroup(arr).split('');
    key[id % 16] = bool ? 2 : 1;
    key = key.join('');
    LIM.$data.setInn(this.arr[arr], Utils.radixNum(parseInt(key), 3, 10));
    return true;
  };

  StorageBool.prototype.getGroup = function(index) {
    return Utils.radixNum(LIM.$data.getInn(this.arr[index]), 10, 3).padZero(16);
  };

  return StorageBool;

})();

LIM.$bool = new StorageBool();
