// Generated by CoffeeScript 1.12.7
var StorageNumber;

StorageNumber = (function() {
  function StorageNumber() {
    this.initialize.apply(this, arguments);
  }

  StorageNumber.prototype = Object.create(StorageNumber.prototype);

  StorageNumber.prototype.constructor = StorageNumber;

  StorageNumber.prototype.initialize = function() {
    this.MAX_Number = 999999999;
    this.MIN_Number = -999999999;
    this.arr = [];
    return true;
  };

  StorageNumber.prototype.get = function(id) {
    if (this.arr[id] != null) {
      return LIM.$data.getInn(this.arr[id]);
    } else {
      return 0;
    }
  };

  return StorageNumber;

})();

LIM.$number = new StorageNumber();
