// Generated by CoffeeScript 1.12.7
var StorageData;

StorageData = (function() {
  function StorageData() {}

  StorageData.dataFile = [];

  StorageData.addFile = function() {
    this.dataFile.push({
      src: "Lim_Audio.json",
      name: "audio"
    });
    this.dataFile.push({
      src: "Lim_Card.json",
      name: "card"
    });
    this.loadDatabase();
    return true;
  };

  StorageData.loadDatabase = function() {
    var i, item, len, ref, results;
    ref = this.dataFile;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      item = ref[i];
      this.loadDataFile(item.name, item.src);
      results.push(true);
    }
    return results;
  };

  StorageData.loadDataFile = function(name, src) {
    var url, xhr;
    xhr = new XMLHttpRequest();
    url = "data/" + src;
    LIM[name] = null;
    xhr.open("GET", url);
    xhr.overrideMimeType`application/json`;
    xhr.onload = (function(_this) {
      return function() {
        return _this.onXhrLoad(xhr, name, src, url);
      };
    })(this);
    return xhr.send();
  };

  StorageData.onXhrLoad = function(xhr, name, src, url) {
    if (xhr.status < 400) {
      LIM[name] = JSON.parse(xhr.responseText);
    }
    return true;
  };

  return StorageData;

})();

StorageData.addFile();
