// Generated by CoffeeScript 1.12.7
var Rogue;

Rogue = (function() {
  function Rogue() {
    this.initialize.apply(this, arguments);
  }

  Rogue.prototype = Object.create(Rogue.prototype);

  Rogue.prototype.constructor = Rogue;

  Object.defineProperties(Rogue.prototype, {
    use_len: {
      get: function() {
        return this.use_room.length;
      },
      configurable: true
    },
    use_room: {
      get: function() {
        return this.room.filter(function(item) {
          return item.exist;
        });
      },
      configurable: true
    },
    empty_room: {
      get: function() {
        return this.room.filter(function(item) {
          return !item.exist;
        });
      },
      configurable: true
    },
    cont1_room: {
      get: function() {
        return this.empty_room.filter(function(item) {
          return item.room_exin.length === 1;
        });
      },
      configurable: true
    },
    cont2_room: {
      get: function() {
        return this.empty_room.filter(function(item) {
          return item.room_exin.length === 2;
        });
      },
      configurable: true
    },
    cont3_room: {
      get: function() {
        return this.empty_room.filter(function(item) {
          return item.room_exin.length === 3;
        });
      },
      configurable: true
    },
    cont4_room: {
      get: function() {
        return this.empty_room.filter(function(item) {
          return item.room_exin.length === 4;
        });
      },
      configurable: true
    },
    room_scope: {
      get: function() {
        return [
          this.room.filter(function(item) {
            return item.scope === 1;
          }), this.room.filter(function(item) {
            return item.scope === 2;
          }), this.room.filter(function(item) {
            return item.scope === 3;
          }), this.room.filter(function(item) {
            return item.scope === 4;
          }), this.room.filter(function(item) {
            return item.scope === 5;
          })
        ];
      },
      configurable: true
    }
  });

  Rogue.prototype.initialize = function(w, h, use, mode) {
    this.seed_mode = 99;
    this.room = [];
    this.use = Math.min(use, w * h);
    this.w = Number(w);
    this.h = Number(h);
    this.mode = mode || 0;
    this.initSpace();
    this.initScope();
    return true;
  };

  Rogue.prototype.initSpace = function() {
    var i, j, ref;
    for (i = j = 0, ref = this.w * this.h - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      this.room[i] = new Room(i % this.w, parseInt(i / this.w), this);
    }
    this.room[LIM.$data.pro(this.seed_mode, this.w * this.h)].padExist();
    while (this.use_len < this.use) {
      if (this.cont1_room.length) {
        this.cont1_room[LIM.$data.pro(this.seed_mode, this.cont1_room.length)].exist = true;
      } else if (this.cont2_room.length) {
        this.cont2_room[LIM.$data.pro(this.seed_mode, this.cont2_room.length)].exist = true;
      } else if (this.cont3_room.length) {
        this.cont3_room[LIM.$data.pro(this.seed_mode, this.cont3_room.length)].exist = true;
      } else if (this.cont4_room.length) {
        this.cont4_room[LIM.$data.pro(this.seed_mode, this.cont4_room.length)].exist = true;
      } else {
        return;
      }
    }
    return true;
  };

  Rogue.prototype.initScope = function() {
    var i, max, min, num, p, results, s, state;
    this.triangle = [];
    while (this.triangle.length < Math.min(3, this.use_room.length)) {
      num = LIM.$data.pro(this.seed_mode, this.use_room.length);
      if (this.triangle.indexOf(num) === -1) {
        this.triangle.push(num);
      }
    }
    this.origin = [];
    for (i in this.room) {
      p = this.use_room[this.triangle[0]].room_distance[i];
      p += this.use_room[this.triangle[1]].room_distance[i];
      this.origin[i] = p;
    }
    min = Math.min.apply(null, this.origin.filter(function(item) {
      return item > -1;
    }));
    max = Math.max.apply(null, this.origin);
    state = parseInt((max - min) / 5);
    results = [];
    for (i in this.room) {
      s = this.room[i].exist ? parseInt((this.origin[i] - min) / state) + 1 : -1;
      results.push(this.room[i].scope = Math.min(s, 5));
    }
    return results;
  };

  return Rogue;

})();
