// Generated by CoffeeScript 1.12.7
var Room;

Room = (function() {
  function Room() {
    this.initialize.apply(this, arguments);
  }

  Room.prototype = Object.create(Room.prototype);

  Room.prototype.constructor = Room;

  Object.defineProperties(Room.prototype, {
    room_id: {
      get: function() {
        return this.y * this.rogue.w + this.x;
      },
      configurable: true
    },
    room_up: {
      get: function() {
        if (this.room_id / this.rogue.w < 1) {
          return null;
        } else {
          return this.rogue.room[this.room_id - this.rogue.w];
        }
      },
      configurable: true
    },
    room_down: {
      get: function() {
        if (this.room_id / this.rogue.w > this.rogue.h - 1) {
          return null;
        } else {
          return this.rogue.room[this.room_id + this.rogue.w];
        }
      },
      configurable: true
    },
    room_left: {
      get: function() {
        if (this.room_id % this.rogue.w === 0) {
          return null;
        } else {
          return this.rogue.room[this.room_id - 1];
        }
      },
      configurable: true
    },
    room_right: {
      get: function() {
        if (this.room_id % this.rogue.w === this.rogue.w - 1) {
          return null;
        } else {
          return this.rogue.room[this.room_id + 1];
        }
      },
      configurable: true
    },
    room_neigh: {
      get: function() {
        return [this.room_down, this.room_left, this.room_right, this.room_up].filter(function(item) {
          return item;
        });
      },
      configurable: true
    },
    room_exin: {
      get: function() {
        return this.room_neigh.filter(function(item) {
          return item.exist;
        });
      },
      configurable: true
    },
    room_vain: {
      get: function() {
        return this.room_neigh.filter(function(item) {
          return !item.exist;
        });
      },
      configurable: true
    },
    room_equative: {
      get: function() {
        return this.room_exin.filter(function(item) {
          return item.scope === this.scope;
        });
      },
      configurable: true
    },
    room_way: {
      get: function() {
        return this.room_exin.filter(function(item) {
          return item.door.indexOf(item.room_id) > -1;
        });
      },
      configurable: true
    },
    room_cut: {
      get: function() {
        return this.room_exin.filter(function(item) {
          return item.door.indexOf(item.room_id) === -1;
        });
      },
      configurable: true
    },
    room_equa_way: {
      get: function() {
        return this.room_equative.filter(function(item) {
          return item.door.indexOf(item.room_id) === -1;
        });
      },
      configurable: true
    },
    room_equa_cut: {
      get: function() {
        return this.room_equative.filter(function(item) {
          return item.door.indexOf(item.room_id) === -1;
        });
      },
      configurable: true
    },
    room_distance: {
      get: function() {
        var arr;
        arr = Utils.fillArray(this.rogue.room.length, -1);
        arr[this.room_id] = 0;
        arr = this.padDistance(arr, 1);
        return arr;
      },
      configurable: true
    },
    way_distance: {
      get: function() {
        var arr;
        arr = Utils.fillArray(this.rogue.room.length, -1);
        arr[this.room_id] = 0;
        arr = this.padEnter(arr, 1);
        return arr;
      },
      configurable: true
    },
    room_diff: {
      get: function() {
        return this.room_vain.reduce(function(r, item) {
          return r + item.room_vain.length;
        }, 0);
      },
      configurable: true
    }
  });

  Room.prototype.initialize = function(x, y, rogue) {
    this.rogue = rogue;
    this.exist = false;
    this.x = x;
    this.y = y;
    this.index = 0;
    this.scope = 0;
    this.prev = null;
    this.door = [-1, -1, -1, -1];
    return true;
  };

  Room.prototype.padExist = function() {
    var e;
    try {
      switch (this.rogue.mode) {
        case 0:
          this.pad();
          break;
        case 1:
          this.padWide(0);
          break;
        case 2:
          this.padWide(1);
          break;
        case 3:
          this.padWide(2);
          break;
        case 4:
          this.padNarrow(8);
          break;
        case 5:
          this.padNarrow(4);
          break;
        case 6:
          this.padNarrow(2);
          break;
        case 7:
          this.padNarrow(0);
      }
      return true;
    } catch (error) {
      e = error;
      return console.log(e);
    }
  };

  Room.prototype.pad = function(prev) {
    if (this.rogue.use <= this.rogue.use_len) {
      return;
    }
    if (this.prev === null && prev) {
      this.prev = prev;
    }
    this.exist = true;
    if (this.room_vain.length) {
      return this.room_vain[LIM.$data.pro(this.rogue.seed_mode + (this.rogue.use_len % 50), this.room_vain.length)].pad(this);
    } else if (this.prev) {
      return this.prev.pad();
    }
  };

  Room.prototype.padWide = function(d, prev) {
    var arr, i, item, j, k, len, ref, ref1;
    if (d == null) {
      d = 0;
    }
    if (this.rogue.use <= this.rogue.use_len) {
      return;
    }
    if (this.prev === null && prev) {
      this.prev = prev;
    }
    this.exist = true;
    arr = [];
    ref = this.room_vain;
    for (j = 0, len = ref.length; j < len; j++) {
      item = ref[j];
      if (item.room_vain.length > d) {
        for (i = k = 0, ref1 = item.room_vain.length; 0 <= ref1 ? k <= ref1 : k >= ref1; i = 0 <= ref1 ? ++k : --k) {
          arr.push(item);
        }
      }
    }
    if (arr.length) {
      return arr[LIM.$data.pro(this.rogue.seed_mode + (this.rogue.use_len % 50), arr.length)].padWide(d, this);
    } else if (this.prev) {
      return this.prev.padWide(d);
    } else if (d > 0) {
      return this.padWide(d - 1);
    }
  };

  Room.prototype.padNarrow = function(d, prev) {
    var arr, i, item, j, k, len, ref, ref1;
    if (d == null) {
      d = 0;
    }
    if (this.rogue.use <= this.rogue.use_len) {
      return;
    }
    if (this.prev === null && prev) {
      this.prev = prev;
    }
    this.exist = true;
    arr = [];
    ref = this.room_vain;
    for (j = 0, len = ref.length; j < len; j++) {
      item = ref[j];
      if (item.room_diff > d) {
        for (i = k = 0, ref1 = item.room_diff; 0 <= ref1 ? k <= ref1 : k >= ref1; i = 0 <= ref1 ? ++k : --k) {
          arr.push(item);
        }
      }
    }
    if (arr.length) {
      return arr[LIM.$data.pro(this.rogue.seed_mode + (this.rogue.use_len % 50), arr.length)].padNarrow(d, this);
    } else if (this.prev) {
      return this.prev.padNarrow(d);
    }
  };

  Room.prototype.padDistance = function(arr, d) {
    var ex, j, k, len, len1, ref, room;
    ex = [];
    ref = this.room_exin;
    for (j = 0, len = ref.length; j < len; j++) {
      room = ref[j];
      if (arr[room.room_id] === -1 || arr[room.room_id] > d) {
        arr[room.room_id] = d;
        ex.push(room);
      }
    }
    for (k = 0, len1 = ex.length; k < len1; k++) {
      room = ex[k];
      arr = room.padDistance(arr, d + 1);
    }
    return arr;
  };

  Room.prototype.padEnter = function(arr, d) {
    var ex, j, k, len, len1, ref, room;
    ex = [];
    ref = this.room_way;
    for (j = 0, len = ref.length; j < len; j++) {
      room = ref[j];
      if (arr[room.room_id] === -1 || arr[room.room_id] > d) {
        arr[room.room_id] = d;
        ex.push(room);
      }
    }
    for (k = 0, len1 = ex.length; k < len1; k++) {
      room = ex[k];
      arr = room.padEnter(arr, d + 1);
    }
    return arr;
  };

  return Room;

})();
