// Generated by CoffeeScript 1.12.7
var LIM, ModuleManager;

ModuleManager = (function() {
  function ModuleManager() {}

  ModuleManager.module = [];

  ModuleManager._path = '';

  ModuleManager._scripts = [];

  ModuleManager._errorUrls = [];

  ModuleManager.install = function() {
    var audio, core, input, js, libs, module, storage;
    js = {
      src: 'js',
      data: []
    };
    libs = {
      src: 'libs',
      data: []
    };
    libs.data.push({
      src: "pixi"
    });
    libs.data.push({
      src: "crypto-js.min"
    });
    libs.data.push({
      src: "localforage.min"
    });
    libs.data.push({
      src: "tone"
    });
    module = {
      src: "module",
      data: []
    };
    core = {
      src: '01-core',
      data: []
    };
    core.data.push({
      src: "00-util"
    });
    core.data.push({
      src: "01-world"
    });
    core.data.push({
      src: "02-stage"
    });
    core.data.push({
      src: "03-shape"
    });
    core.data.push({
      src: "04-manager"
    });
    module.data.push(core);
    storage = {
      src: '02-storage',
      data: []
    };
    storage.data.push({
      src: "01-main"
    });
    storage.data.push({
      src: "02-save"
    });
    storage.data.push({
      src: "03-boolean"
    });
    storage.data.push({
      src: "04-number"
    });
    storage.data.push({
      src: "05-data"
    });
    module.data.push(storage);
    audio = {
      src: '03-audio',
      data: []
    };
    audio.data.push({
      src: "01-conductor"
    });
    module.data.push(audio);
    input = {
      src: '04-input',
      data: []
    };
    input.data.push({
      src: "01-keyboard"
    });
    input.data.push({
      src: "02-touch"
    });
    module.data.push(input);
    js.data.push(libs);
    js.data.push(module);
    js.data.push({
      src: "main"
    });
    this.module.push(js);
    return true;
  };

  ModuleManager.setup = function(modules, src) {
    var i, len, module, name;
    for (i = 0, len = modules.length; i < len; i++) {
      module = modules[i];
      if (module.data) {
        this.setup(module.data, src + "/" + module.src);
      } else {
        name = src + "/" + module.src + ".js";
        this.loadScript(name);
        this._scripts.push(name);
      }
    }
    return true;
  };

  ModuleManager.loadScript = function(url) {
    var script;
    script = script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = "https://66t.github.io/rururm/" + url + "?" + (Math.random() * 10000);
    script.async = false;
    script._url = url;
    script.onerror = this.onError.bind(this);
    document.body.appendChild(script);
    return true;
  };

  ModuleManager.onError = function(e) {
    this._errorUrls.push(e.target._url);
    return true;
  };

  ModuleManager.load = function() {
    var base, e, path;
    this.install();
    try {
      path = require('path');
      base = path.dirname(process.mainModule.filename);
      this.setup(this.module, base.slice(0, -1));
    } catch (error) {
      e = error;
      this.setup(this.module, "");
    }
    return true;
  };

  return ModuleManager;

})();

LIM = {};

ModuleManager.load();
