// Generated by CoffeeScript 1.12.7
var Touch;

Touch = (function() {
  function Touch() {}

  Touch.active = true;

  Touch.repeatTime = 25;

  Touch.keyTable = {};

  Touch.install = function() {
    document.addEventListener('mouseup', this.onUp.bind(this));
    document.addEventListener('mousedown', this.onDown.bind(this));
    document.addEventListener('touchstart', this.onDown.bind(this));
    document.addEventListener('touchend', this.onUp.bind(this));
    document.addEventListener('wheel', this.onWheel.bind(this));
    return true;
  };

  Touch.onDown = function(event) {
    this.keyTable[event.button] = {
      keyTime: performance.now(),
      upTime: -1,
      count: 0
    };
    return true;
  };

  Touch.onUp = function(event) {
    if (this.keyTable[event.button]) {
      this.keyTable[event.button].upTime = performance.now();
    }
    return true;
  };

  Touch.onWheel = function(event) {
    if (event.deltaY < 0) {
      this.keyTable[100] = {
        keyTime: performance.now(),
        upTime: -1,
        count: 0
      };
    } else {
      this.keyTable[101] = {
        keyTime: performance.now(),
        upTime: -1,
        count: 0
      };
    }
    return true;
  };

  Touch.update = function() {
    var key, ref, table;
    if (!this.active) {
      return;
    }
    ref = this.keyTable;
    for (key in ref) {
      table = ref[key];
      if (table.keyTime > table.upTime) {
        table.count++;
      } else if (table.count > 0) {
        table.count = -1;
      } else {
        table.count--;
      }
    }
    return true;
  };

  Touch.isPress = function(c) {
    if (this.keyTable[c] && this.keyTable[c].count === 1) {
      return true;
    }
    return false;
  };

  Touch.isRepeatPress = function(c, time) {
    if (this.keyTable[c] && this.keyTable[c].count > 0 && this.keyTable[c].count % (time || this.repeatTime) === 0) {
      return true;
    }
    return false;
  };

  Touch.isReleasPress = function(c) {
    if (this.keyTable[c] && this.keyTable[c].count === -1) {
      return true;
    }
    return false;
  };

  return Touch;

})();

Touch.install();
