// Generated by CoffeeScript 1.12.7
var Utils;

Number.prototype.padZero = function(length) {
  return String(this.padZero(length));
};

String.prototype.padZero = function(length) {
  return this.padStart(length, '0');
};

String.prototype.format = function() {
  return this.replace(/%([0-9]+)/g, function(s, n) {
    return arguments[Number(n) - 1];
  });
};

String.prototype.replaceSymbol = function(arr) {
  return arr.reduce(function(result, value, i) {
    return result.replace(new RegExp("%\\[" + (i + 1) + "\\]", 'g'), value, this);
  });
};

String.prototype.getLen = function() {
  var i, k, l, len, ref;
  len = 0;
  l = this.length;
  for (i = k = 0, ref = l; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
    if (this.charCodeAt(i) > 255) {
      len += 2;
    } else {
      len += 1;
    }
  }
  return len;
};

String.prototype.splice = function(start, del, newStr) {
  return this.slice(0, start) + (newStr || "") + this.slice(start + del);
};

Number.prototype.clamp = function(min, max) {
  return Math.min(Math.max(this, min), max);
};

Math.randomInt = function(max) {
  return Math.floor(max * Math.random());
};

Array.prototype.clone = function() {
  return this.slice(0);
};

Array.prototype.equals = function(array) {
  var i, k, ref;
  if (!array || this.length !== array.length) {
    return false;
  }
  for (i = k = 0, ref = this.length; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
    if (this[i] instanceof Array && array[i] instanceof Array) {
      if (!this[i].equals(array[i])) {
        return false;
      }
    } else if (this[i] !== array[i]) {
      return false;
    }
  }
  return true;
};

Object.defineProperty(Array.prototype, "equals", {
  enumerable: false
});

Object.defineProperty(Array.prototype, "clone", {
  enumerable: false
});

Utils = (function() {
  function Utils() {}

  Utils.escapeHtml = function(str) {
    var entityMap;
    entityMap = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#39;',
      '/': '&#x2F;'
    };
    return String(str).replace(/[&<>"'\/]/g, function(s) {
      return entityMap[s];
    });
  };

  Utils.encodeURI = function(str) {
    return encodeURIComponent(str).replace(/%2F/g, '/');
  };

  Utils.isNwjs = function() {
    return typeof require === 'function' && typeof process === 'object';
  };

  Utils.radixNum = function(num, m, n) {
    var _DEFAULT_;
    num = typeof num === 'string' ? num : String(num);
    _DEFAULT_ = {
      initNum: 10
    };
    m = m === 0 ? _DEFAULT_.initNum : m;
    n = n === 0 ? _DEFAULT_.initNum : n;
    n = m && !n ? _DEFAULT_.initNum : n;
    return parseInt(num, m).toString(n);
  };

  Utils.rpgaReduce = function(r, g, b, a) {
    return this.radixNum(Math.min(r || 255, 255), 10, 16) + this.radixNum(Math.min(g || 255, 255), 10, 16) + this.radixNum(Math.min(b || 255, 255), 10, 16) + this.radixNum(Math.min(a || 255, 255), 10, 16);
  };

  Utils.commonDiv = function(a, b) {
    if (b === 0) {
      return a;
    } else {
      return this.commonDiv(b, a % b);
    }
  };

  Utils.commonMul = function(a, b) {
    return a * b / this.commonDiv(a, b);
  };

  Utils.rooting = function(a, b) {
    return Math.pow(Math.abs(a), 1 / b);
  };

  Utils.bottnum = function(a, b) {
    return Math.log(a) / Math.log(b);
  };

  Utils.azimuth = function(dual, angle, d) {
    return {
      x: dual.x + d * Math.cos(angle),
      y: dual.y + d * Math.sin(angle)
    };
  };

  Utils.fractionOth = function(son, mum) {
    var div;
    div = 100;
    while (div > 1) {
      div = this.commonDiv(son, mum);
      son /= div;
      mum /= div;
    }
    return [son, mum];
  };

  Utils.fractionExp = function(num) {
    return this.fractionOth(num, Math.pow(10, num.toString().length));
  };

  Utils.angelPrime = function(num) {
    var arr, i;
    arr = [2, 3];
    i = 5;
    while (arr.length < num) {
      if (!arr.some(function(n) {
        return i % n === 0 && n * n <= i;
      })) {
        arr.push(i);
      }
      i += i % 6 === 1 ? 4 : 2;
    }
    return arr;
  };

  Utils.getNormalRandom = function(base, d, b, sd, sb) {
    var num, t;
    base += 1;
    d += 2;
    t = this.normalRandom();
    num = parseInt(base + t * (t > 0 ? (sd * 5 * d) / d : sb ? sb * 5 * b : (sd * 5 * b) / b)).clamp(base - d, base + b);
    if (num <= base - d || num >= base + b) {
      return this.getNormalRandom(base - 1, d - 2, b, sd, sb);
    } else {
      return num;
    }
  };

  Utils.normalRandom = function() {
    var c, u, v, w;
    u = 0.0;
    v = 0.0;
    w = 0.0;
    c = 0.0;
    while (true) {
      u = Math.random() * 2 - 1;
      v = Math.random() * 2 - 1;
      w = u * u + v * v;
      if (w !== 0 && w <= 1) {
        break;
      }
    }
    c = Math.sqrt((-2 * Math.log(w)) / w);
    return u * c;
  };

  Utils.isNum = function(num) {
    return num !== null && num !== '' && !isNaN(num);
  };

  Utils.D = function(s, seed) {
    var _, k, numDice, numSides, ref, ref1, roll, total;
    ref = s.match(/(\d+)d(\d+)/).slice(1, 3), numDice = ref[0], numSides = ref[1];
    total = 0;
    for (_ = k = 1, ref1 = numDice; 1 <= ref1 ? k <= ref1 : k >= ref1; _ = 1 <= ref1 ? ++k : --k) {
      roll = seed ? LIM.$data.pro(seed, numSides) + 1 : Math.floor(Math.random() * numSides) + 1;
      total += roll;
    }
    return total;
  };

  Utils.sinNum = function(max, i) {
    return Math.sin(Math.PI / 2 / max * i).toFixed(7);
  };

  Utils.atBit = function(num, bit) {
    return num >> bit & 1;
  };

  Utils.setBit = function(num, bit, bool) {
    if (bool) {
      return num | (1 << bit);
    } else {
      return num & ~(1 << bit);
    }
  };

  Utils.lengthNum = function(num) {
    var _, a, b, e, ref, ref1;
    try {
      if (!isNaN(num)) {
        return parseFloat(num);
      }
      if (num.match(/(\d+)w(\d*)/)) {
        ref = num.match(/(\d+)w(\d*)/), _ = ref[0], a = ref[1], b = ref[2];
        return parseFloat(a) * 0.01 * World.canvasWidth + parseFloat(b || 0);
      } else if (num.match(/(\d+)h(\d*)/)) {
        ref1 = num.match(/(\d+)h(\d*)/), _ = ref1[0], a = ref1[1], b = ref1[2];
        return parseFloat(a) * 0.01 * World.canvasHeight + parseFloat(b || 0);
      } else {
        return 0;
      }
    } catch (error) {
      e = error;
      return 0;
    }
  };

  Utils.shuffleArr = function(arr, seed) {
    var index, newArr;
    if (!Array.isArray(arr)) {
      return [];
    }
    newArr = [];
    while (arr.length) {
      index = seed && LIM.$data ? LIM.$data.pro(seed, arr.length) : Math.floor(Math.random() * arr.length);
      newArr.push(arr.splice(index, 1)[0]);
    }
    return newArr;
  };

  Utils.countingSort = function(arr) {
    var count, i, index, k, len1, len2, min, name, num, o, result;
    if (arr.length <= 1) {
      return arr;
    }
    min = Math.min.apply(null, arr);
    count = [];
    result = [];
    index = 0;
    for (k = 0, len1 = arr.length; k < len1; k++) {
      num = arr[k];
      if (count[name = num - min] == null) {
        count[name] = 0;
      }
    }
    for (o = 0, len2 = arr.length; o < len2; o++) {
      num = arr[o];
      count[num - min]++;
    }
    while ((function() {
        var p, ref, results;
        results = [];
        for (i = p = 0, ref = count.length; 0 <= ref ? p < ref : p > ref; i = 0 <= ref ? ++p : --p) {
          results.push(count[i]-- > 0);
        }
        return results;
      })()) {
      result[index++] = i + min;
    }
    return result;
  };

  Utils.quickSort = function(arr) {
    var k, left, len1, num, pivot, right;
    if (arr.length <= 1) {
      return arr;
    }
    pivot = arr.splice(Math.floor(arr.length / 2), 1)[0];
    left = [];
    right = [];
    for (k = 0, len1 = arr.length; k < len1; k++) {
      num = arr[k];
      if (num < pivot) {
        left.push(num);
      } else {
        right.push(num);
      }
    }
    return this.quickSort(left).concat([pivot], this.quickSort(right));
  };

  Utils.getCombinations = function(array, s) {
    var combinations, i, indices, j, k, length, ref, ref1, sortedArray;
    combinations = [];
    length = array.length;
    if (s <= 0 || s > length) {
      return combinations;
    }
    sortedArray = array.slice().sort(function(a, b) {
      return a - b;
    });
    indices = (function() {
      var k, ref, results;
      results = [];
      for (i = k = 0, ref = s; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
        results.push(i);
      }
      return results;
    })();
    while (indices[0] <= length - s) {
      combinations.push(indices.map(function(i) {
        return sortedArray[i];
      }));
      i = s - 1;
      while (i >= 0 && indices[i] === i + length - s) {
        i--;
      }
      if (i < 0) {
        break;
      }
      indices[i]++;
      for (j = k = ref = i + 1, ref1 = s; ref <= ref1 ? k < ref1 : k > ref1; j = ref <= ref1 ? ++k : --k) {
        indices[j] = indices[j - 1] + 1;
      }
    }
    return combinations;
  };

  Utils.getPermute = function(array) {
    var backtrack, result;
    result = [];
    backtrack = function(current, remaining) {
      var i, k, ref, ref1, results;
      if (remaining.length === 0) {
        result.push(current.slice());
        return;
      }
      results = [];
      for (i = k = 0, ref = remaining.length; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
        ref1 = [remaining[0], remaining[i]], remaining[i] = ref1[0], remaining[0] = ref1[1];
        current.push(remaining.shift());
        backtrack(current, remaining);
        results.push(remaining.unshift(current.pop()));
      }
      return results;
    };
    backtrack([], array);
    return result;
  };

  Utils.calcAngle = function(x1, y1, x2, y2) {
    var angle, deltaX, deltaY;
    deltaX = x2 - x1;
    deltaY = y2 - y1;
    angle = Math.atan2(deltaY, deltaX) * (180 / Math.PI);
    if (angle < 0) {
      angle += 360;
    }
    return angle;
  };

  Utils.fillArray = function(num, item) {
    return Array(num).fill(item);
  };

  Utils.union = function(array1, array2) {
    return array1.concat(array2).filter(function(item, index, self) {
      return self.indexOf(item) === index;
    });
  };

  Utils.Difference = function(array1, array2) {
    return array1.filter(function(item) {
      return array2.indexOf(item) === -1;
    });
  };

  Utils.Intersection = function(array1, array2) {
    return array1.filter(function(item) {
      return array2.indexOf(item) !== -1;
    });
  };

  Utils.reverseString = function(input) {
    return input.split('').reverse().join('');
  };

  Utils.sortBy = function(property, desc) {
    if (desc == null) {
      desc = false;
    }
    return function(v1, v2) {
      var ref;
      return ((ref = v2[property] > v1[property]) != null ? ref : {
        1: -1
      }) * (desc ? -1 : 1);
    };
  };

  return Utils;

})();

window.document.oncontextmenu = function() {
  return false;
};
