// Generated by CoffeeScript 1.12.7
var World;

World = (function() {
  function World() {}

  World.canvasWidth = 16 * 128;

  World.canvasHeight = 9 * 128;

  World.windowWidth = 0;

  World.windowHeight = 0;

  World.scale = 1;

  World.app = null;

  World.tick = null;

  World.clock = [0, 0, 0, 0, 0, 0];

  World.cursor = [0, 0];

  World.canvas = {
    x: 0,
    y: 0,
    w: 0,
    h: 0
  };

  World.showFps = false;

  World.init = function() {
    PIXI.utils.skipHello();
    PIXI.settings.GC_MAX_IDLE = 600;
    this.initCanvas();
    this.initFps();
    this.initFont();
    this.updateFps();
    this.setupEventHandlers();
    this.resize();
    return true;
  };

  World.initCanvas = function() {
    var e;
    try {
      this.app = new PIXI.Application({
        width: this.canvasWidth,
        height: this.canvasHeight,
        resolution: window.devicePixelRatio,
        antialias: true,
        autoStart: false
      });
      PIXI.settings.PREFER_ENV = PIXI.ENV.WEBGL;
      document.body.appendChild(this.app.view);
      this.app.view.style.display = "none";
      this.app.view.style.position = "absolute";
      this.app.ticker.remove(this.app.render, this.app);
      this.app.ticker.add(this.onTick, this);
      this.clock[2] = 100;
      this.clock[1] = performance.now() - 100;
      return true;
    } catch (error) {
      e = error;
      this._app = null;
      return false;
    }
  };

  World.startGame = function() {
    if (this.app) {
      this.app.start();
    }
    return true;
  };

  World.stopGame = function() {
    if (this.app) {
      this.app.stop();
    }
    return true;
  };

  World.initFps = function() {
    this.fps = document.createElement("div");
    this.memory = document.createElement("div");
    this.xy = document.createElement("div");
    document.body.appendChild(this.fps);
    this.fps.style.width = "200px";
    this.fps.style.height = "30px";
    this.fps.style.top = "30px";
    this.fps.style.left = "10px";
    this.fps.style.lineHeight = "30px";
    this.fps.style.position = "absolute";
    this.fps.style.backgroundColor = "#000a";
    this.fps.style.color = "#fff";
    this.fps.style.fontSize = "18px";
    this.fps.style.fontWeight = "800";
    this.fps.style.textAlign = "left";
    this.fps.style.pointerEvents = "none";
    document.body.appendChild(this.memory);
    this.memory.style.width = "200px";
    this.memory.style.height = "30px";
    this.memory.style.left = "10px";
    this.memory.style.lineHeight = "30px";
    this.memory.style.position = "absolute";
    this.memory.style.backgroundColor = "#000a";
    this.memory.style.color = "#fff";
    this.memory.style.fontSize = "18px";
    this.memory.style.fontWeight = "800";
    this.memory.style.textAlign = "left";
    this.memory.style.pointerEvents = "none";
    document.body.appendChild(this.xy);
    this.xy.style.width = "200px";
    this.xy.style.height = "30px";
    this.xy.style.top = "60px";
    this.xy.style.left = "10px";
    this.xy.style.lineHeight = "30px";
    this.xy.style.position = "absolute";
    this.xy.style.backgroundColor = "#000a";
    this.xy.style.color = "#fff";
    this.xy.style.fontSize = "18px";
    this.xy.style.fontWeight = "800";
    this.xy.style.textAlign = "left";
    this.xy.style.pointerEvents = "none";
    return true;
  };

  World.updateFps = function() {
    if (this.showFps) {
      this.fps.style.display = 'block';
      this.xy.style.display = 'block';
      this.memory.style.display = 'block';
    } else {
      this.fps.style.display = 'none';
      this.xy.style.display = 'none';
      this.memory.style.display = 'none';
    }
    return true;
  };

  World.drawFps = function() {
    this.fps.innerHTML = "fps: " + (this.clock[3].toFixed(0));
    this.memory.innerHTML = ((performance.memory.usedJSHeapSize / 1048576).toFixed(2)) + "MB";
    this.xy.innerHTML = (this.cursor[0].toFixed(0)) + "/" + (this.cursor[1].toFixed(0));
    return true;
  };

  World.setStage = function(stage) {
    if (this.app) {
      this.app.stage = stage;
    }
    return true;
  };

  World.canRender = function() {
    return !!this.app.stage;
  };

  World.initFont = function() {
    FontManager.load("cubic", "cubic.ttf");
    FontManager.load("ht", "ZiXinFangShenShiHei-2.ttf");
    return true;
  };

  World.setTick = function(handler) {
    this.tick = handler;
    return true;
  };

  World.onTick = function(deltaTime) {
    var thisclockTime, time;
    this.clock[0] = performance.now();
    if (this.tick) {
      this.tick(deltaTime);
    }
    if (this.canRender()) {
      this.app.render();
    }
    time = performance.now();
    thisclockTime = time - this.clock[1];
    this.clock[2] += (thisclockTime - this.clock[2]) / 12;
    this.clock[3] = 1000 / this.clock[2];
    this.clock[4] = Math.max(0, time - this.clock[0]);
    this.clock[1] = time;
    if (this.clock[5]++ % 15 === 0) {
      this.drawFps();
    }
    return true;
  };

  World.resize = function() {
    var scale;
    this.windowWidth = window.innerWidth;
    this.windowHeight = window.innerHeight;
    scale = Math.min(this.windowWidth / this.app.view.width, this.windowHeight / this.app.view.height);
    this.setScale(scale);
    return true;
  };

  World.changeResolution = function(w, h) {
    this.scale = 1;
    w *= window.devicePixelRatio;
    h *= window.devicePixelRatio;
    this.canvasWidth = w;
    this.canvasHeight = h;
    this.app.width = w;
    this.app.height = h;
    this.app.view.width = w;
    this.app.view.height = h;
    this.resize();
    return true;
  };

  World.setScale = function(scale) {
    var canvasOffsetHeight, canvasOffsetWidth, canvasStyle, ref;
    if ((ref = this.app) != null ? ref.view : void 0) {
      this.scale = scale;
      canvasStyle = this.app.view.style;
      canvasOffsetWidth = this.app.view.offsetWidth;
      canvasOffsetHeight = this.app.view.offsetHeight;
      this.canvas.w = canvasOffsetWidth * scale;
      this.canvas.h = canvasOffsetHeight * scale;
      this.canvas.x = (this.windowWidth - this.canvas.w) / 2;
      this.canvas.y = (this.windowHeight - this.canvas.h) / 2;
      canvasStyle.transform = "scale(" + scale + ", " + scale + ")";
      canvasStyle.left = "calc((-" + canvasOffsetWidth + "px * (1 - " + scale + ")) / 2 + (" + this.windowWidth + "px - " + canvasOffsetWidth + "px * " + scale + ") / 2)";
      canvasStyle.top = "calc((-" + canvasOffsetHeight + "px * (1 - " + scale + ")) / 2 + (" + this.windowHeight + "px - " + canvasOffsetHeight + "px * " + scale + ") / 2)";
    }
    return true;
  };

  World.cursorMove = function(event) {
    var sx, sy;
    sx = event.clientX - World.canvas.x;
    sy = event.clientY - World.canvas.y;
    this.cursor = [sx / World.scale / window.devicePixelRatio, sy / World.scale / window.devicePixelRatio];
    return true;
  };

  World.onKeyDown = function(event) {
    if (!(event.ctrlKey || event.altKey)) {
      switch (event.keyCode) {
        case 113:
          this.showFps = !this.showFps;
          this.updateFps();
          break;
        case 115:
          if (this.isFull()) {
            this.cancelFullScreen();
          } else {
            this.requestFullScreen();
          }
          break;
        case 116:
          if (Utils.isNwjs()) {
            chrome.runtime.reload();
          }
      }
    }
    return this;
  };

  World.isFull = function() {
    return document.fullScreenElement || document.mozFullScreen || document.webkitFullscreenElement;
  };

  World.requestFullScreen = function() {
    var element;
    element = document.body;
    if (element.requestFullScreen) {
      return element.requestFullScreen();
    } else if (element.mozRequestFullScreen) {
      return element.mozRequestFullScreen();
    } else if (element.webkitRequestFullScreen) {
      return element.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);
    }
  };

  World.cancelFullScreen = function() {
    var element;
    element = document;
    if (document.cancelFullScreen) {
      return document.cancelFullScreen();
    } else if (document.mozCancelFullScreen) {
      return document.mozCancelFullScreen();
    } else if (document.webkitCancelFullScreen) {
      return document.webkitCancelFullScreen();
    }
  };

  World.change = function() {
    if (document.visibilityState === 'hidden') {
      this.hide();
    } else {
      this.acti();
    }
    return true;
  };

  World.acti = function() {
    Tone.Master.mute = false;
    Keyboard.active = true;
    Touch.active = true;
    return true;
  };

  World.hide = function() {
    Tone.Master.mute = true;
    Keyboard.active = false;
    Touch.active = false;
    return true;
  };

  World.unload = function() {
    PIXI.utils.clearTextureCache();
    return ImageManager.clear();
  };

  World.setupEventHandlers = function() {
    document.addEventListener('mousemove', this.cursorMove.bind(this));
    document.addEventListener('keydown', this.onKeyDown.bind(this));
    window.addEventListener('resize', this.resize.bind(this));
    window.addEventListener('visibilitychange', this.change.bind(this));
    window.addEventListener("unload", this.unload.bind(this));
    return true;
  };

  return World;

})();
