// Generated by CoffeeScript 1.12.7
var Scene, Stage;

Stage = (function() {
  function Stage() {
    this.initialize.apply(this, arguments);
  }

  Stage.prototype = Object.create(PIXI.Container.prototype);

  Stage.prototype.constructor = Stage;

  Stage.prototype.initialize = function() {
    PIXI.Container.call(this);
    this.interactive = false;
    this.started = false;
    this.active = false;
    this.sortableChildren = true;
    return true;
  };

  Stage.prototype.destroy = function() {
    PIXI.Container.prototype.destroy.call(this, {
      children: true,
      texture: true
    });
    return true;
  };

  Stage.prototype.create = function() {
    return true;
  };

  Stage.prototype.isReady = function() {
    return FontManager.isReady() && ImageManager.isReady();
  };

  Stage.prototype.start = function() {
    this.started = true;
    this.active = true;
    return true;
  };

  Stage.prototype.update = function() {
    var child, j, len, ref;
    ref = this.children;
    for (j = 0, len = ref.length; j < len; j++) {
      child = ref[j];
      if (child.update) {
        child.update();
      }
    }
    return true;
  };

  Stage.prototype.popScene = function() {
    Scene.pop();
    return true;
  };

  Stage.prototype.stop = function() {
    this.active = false;
    return true;
  };

  Stage.prototype.isActive = function() {
    return this.active;
  };

  Stage.prototype.isStarted = function() {
    return this.started;
  };

  Stage.prototype.terminate = function() {
    return true;
  };

  return Stage;

})();

Scene = (function() {
  function Scene() {}

  Scene.scene = null;

  Scene.nextScene = null;

  Scene.stack = [];

  Scene.exiting = false;

  Scene.previousScene = null;

  Scene.previousClass = null;

  Scene.smoothDeltaTime = 1;

  Scene.elapsedTime = 0;

  Scene.run = function(sceneClass) {
    var e;
    try {
      this.initialize();
      this.goto(sceneClass);
      World.startGame();
      return true;
    } catch (error) {
      e = error;
      return false;
    }
  };

  Scene.initialize = function() {
    this.initWorld();
    return true;
  };

  Scene.initWorld = function() {
    World.init();
    World.setTick(this.update.bind(this));
    return true;
  };

  Scene.update = function(deltaTime) {
    var e, i, j, n, ref;
    try {
      n = this.determineRepeatNumber(deltaTime);
      for (i = j = 0, ref = n; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        this.updateMain();
      }
    } catch (error) {
      e = error;
    }
    return true;
  };

  Scene.updateMain = function() {
    this.changeScene();
    this.updateScene();
    this.updateOperate();
    return true;
  };

  Scene.updateOperate = function() {
    Keyboard.update();
    Touch.update();
    return true;
  };

  Scene.determineRepeatNumber = function(deltaTime) {
    this.smoothDeltaTime *= 0.8;
    this.smoothDeltaTime += Math.min(deltaTime, 2) * 0.2;
    if (this.smoothDeltaTime >= 0.9) {
      this.elapsedTime = 0;
      Math.round(this.smoothDeltaTime);
    } else {
      this.elapsedTime += deltaTime;
      if (this.elapsedTime >= 1) {
        this.elapsedTime -= 1;
        1;
      } else {
        0;
      }
    }
    return true;
  };

  Scene.terminate = function() {
    if (Utils.isNwjs()) {
      nw.App.quit();
      return true;
    }
  };

  Scene.changeScene = function() {
    if (this.isSceneChanging()) {
      if (this.scene) {
        this.scene.terminate();
        this.onSceneTerminate();
      }
      this.scene = this.nextScene;
      this.nextScene = null;
      if (this.scene) {
        this.scene.create();
      }
      if (this.exiting) {
        this.terminate();
      }
    }
    return true;
  };

  Scene.isSceneChanging = function() {
    return this.exiting || !!this.nextScene;
  };

  Scene.onSceneStart = function() {
    World.setStage(this.scene);
    return true;
  };

  Scene.onSceneTerminate = function() {
    this.previousScene = this.scene;
    this.previousClass = this.scene.constructor;
    World.setStage(null);
    return true;
  };

  Scene.updateScene = function() {
    if (this.scene) {
      if (this.scene.isStarted()) {
        if (this.isGameActive()) {
          this.scene.update();
        }
      } else if (this.scene.isReady()) {
        this.onBeforeSceneStart();
        this.scene.start();
        this.onSceneStart();
      }
    }
    return true;
  };

  Scene.isGameActive = function() {
    var e;
    try {
      window.top.document.hasFocus();
    } catch (error) {
      e = error;
    }
    return true;
  };

  Scene.onBeforeSceneStart = function() {
    if (this.previousScene) {
      this.previousScene.destroy();
      this.previousScene = null;
    }
    return true;
  };

  Scene.goto = function(sceneClass) {
    if (sceneClass) {
      this.nextScene = new sceneClass();
    }
    if (this.scene) {
      this.scene.stop();
    }
    return true;
  };

  Scene.push = function(sceneClass) {
    this.stack.push(this.scene.constructor);
    this.goto(sceneClass);
    return true;
  };

  Scene.pop = function() {
    if (this.stack.length > 0) {
      this.goto(this.stack.pop());
    } else {
      this.exit();
    }
    return true;
  };

  Scene.exit = function() {
    this.goto(null);
    this.exiting = true;
    return true;
  };

  Scene.clearStack = function() {
    this.stack = [];
    return true;
  };

  Scene.stop = function() {
    World.stopGame();
    return true;
  };

  return Scene;

})();
