// Generated by CoffeeScript 1.12.7
var FontManager, ImageManager;

ImageManager = (function() {
  function ImageManager() {}

  ImageManager.cache = {};

  ImageManager.system = {};

  ImageManager.emptyBitmap = new Bitmap(1, 1);

  ImageManager.loadBitmap = function(folder, filename) {
    var url;
    if (filename) {
      url = folder + "/" + (Utils.encodeURI(filename)) + ".png";
      return this.loadBitmapFromUrl(url);
    } else {
      return this.emptyBitmap;
    }
  };

  ImageManager.loadBitmapFromUrl = function(url) {
    var cache;
    cache = url.includes("/system/") ? this.system : this.cache;
    return cache[url] != null ? cache[url] : cache[url] = Bitmap.load(url);
  };

  ImageManager.clear = function() {
    var bitmap, ref, url;
    ref = this.cache;
    for (url in ref) {
      bitmap = ref[url];
      bitmap.destroy();
    }
    this.cache = {};
    return true;
  };

  ImageManager.isReady = function() {
    var bitmap, cache, i, len, ref, url;
    ref = [this._cache, this._system];
    for (i = 0, len = ref.length; i < len; i++) {
      cache = ref[i];
      for (url in cache) {
        bitmap = cache[url];
        if (bitmap.isError()) {
          this.throwLoadError(bitmap);
        }
        if (!bitmap.isReady()) {
          return false;
        }
      }
    }
    return true;
  };

  ImageManager.throwLoadError = function(bitmap) {
    var retry;
    return retry = bitmap.retry.bind(bitmap);
  };

  return ImageManager;

})();

FontManager = (function() {
  function FontManager() {}

  FontManager.urls = {};

  FontManager.states = {};

  FontManager.load = function(family, filename) {
    var url;
    if (this.states[family] === "loaded") {
      return;
    }
    if (filename) {
      url = this.makeUrl(filename);
      return this.startLoading(family, url);
    } else {
      this.urls[family] = "";
      return this.states[family] = "loaded";
    }
  };

  FontManager.isReady = function() {
    var family, ref, state;
    ref = this.states;
    for (family in ref) {
      state = ref[family];
      if (state === "loading") {
        return false;
      }
      if (state === "error") {
        this.throwLoadError(family);
      }
    }
    return true;
  };

  FontManager.startLoading = function(family, url) {
    var font, source;
    source = "url(" + url + ")";
    font = new FontFace(family, source);
    this.urls[family] = url;
    this.states[family] = "loading";
    return font.load().then(function() {
      document.fonts.add(font);
      FontManager.states[family] = "loaded";
      return 0;
    })["catch"](function() {
      FontManager.states[family] = "error";
      return false;
    });
  };

  FontManager.throwLoadError = function(family) {
    var retry, url;
    url = this.urls[family];
    retry = function() {
      return this.startLoading(family, url);
    };
    throw ["LoadError", url, retry];
  };

  FontManager.makeUrl = function(filename) {
    return "fonts/" + (Utils.encodeURI(filename));
  };

  return FontManager;

})();
